### ISSUE TITLE
Ioncube Error

### ISSUE THREAD

**Issue by whitetiger264** [DomainNameServices/Gateway-WHMCS#13]
Our WHMCS currently runs on PHP 7.4. We have tested IonCube 10 - 12 and we're constantly presented with this error:

```
Whoops\Exception\ErrorException: The file .../modules/registrars/dns_gateway/dns_gateway.php encoded as type [1/81] cannot be decoded by this version of the ionCube Loader.
in Unknown:0
Stack trace:
#0 ../vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(16, 'The file /home/...', 'Unknown', 0)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}
```

What's the minimum required PHP version and IonCube loader version?

**Comment by whitetiger264** [comment]
Also testing it with PHP 8.1 Ioncube 12 via WHMCS 8.8.0 and manually executing cron via CLI to run throws the following:

```
[root@xxxx]# php cron.php 
Whoops\Exception\ErrorException: The file .../modules/registrars/dns_gateway/hooks.php encoded as type [1/81] cannot be decoded by this version of the ionCube Loader.
 in Unknown:0

#0 ../vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(16, 'The file /home/...', 'Unknown', 0)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}[root@mercury crons]# 

```

**Comment by davidkinnes** [comment]
We are now publishing the un-encoded code so should no longer be an issue
