### ISSUE TITLE
Signature has expired | 4.0.70

### ISSUE THREAD

**Issue by whitetiger264** [DomainNameServices/Gateway-WHMCS#14]
Good Day

The latest version was working great until this morning when I wanted to manage domain names via WHMCS I now get this:

``` 
WHMCS\Module\Registrar\dns_gateway\RestAPIException: Signature has expired. in /home/xxx/public_html/billing/modules/registrars/dns_gateway/lib/DNSAPI.php:300
Stack trace:
#0 /home/xxx/public_html/billing/modules/registrars/dns_gateway/lib/DNSAPI.php(175): WHMCS\Module\Registrar\dns_gateway\DNSAPI->execCH(Resource id #577)
#1 /home/xxx/public_html/billing/modules/registrars/dns_gateway/lib/DNSAPI.php(675): WHMCS\Module\Registrar\dns_gateway\DNSAPI->getCH('https://srs-epp...')
#2 /home/xxx/public_html/billing/modules/registrars/dns_gateway/dns_gateway.php(1532): WHMCS\Module\Registrar\dns_gateway\DNSAPI->domain_sync('domain.af...')
#3 /home/xxx/public_html/billing/admin/clientsdomains.php(0): dns_gateway_AdminCustomButtonArray(Array)
#4 {main}
```

**Comment by davidkinnes** [comment]
Hi, I'm looking into this issue

**Comment by davidkinnes** [comment]
Hi version 4.0.72 has been added with a fix for this issue.
